 Title: Modulblog BAIN
 Author: Ibrahim Akoezel
 E-Mail: ibrahim.akoezel@stud.fhgr.ch
 Description: Einblick in Bibliotheken und Archiven eingesetzten Softwares und Technologien 
 Theme: Bibliothek, Archiv, Informatik, Open Source
 Github_username: akoezeibrahi
theme: jekyll-theme-time-machine
